configuration:
  maxEntries: 10
services:
  - name: Search Code/Name
    sourceFile: ./test.csv
    fileType: csv
    fields:
      - name: NEW CODE
        search: true
        displayName: Code
      - name: Business Name
        search: true
        primary: true
        displayName: Business
      - name: Office Address / Location
        displayName: Address
      - name: Email
        search: true
        display: true
      - name: Phone Number
        search: true
        displayName: Phone
      - name: Mobile Number
        search: true
        displayName: Mobile
      - name: Name
        displayName: First Name
      - name: Last Name
        display: true
    fileSettings:
      numberSkipRows: 2
