configuration:
  maxEntries: 10
services:
  - name: QR Code Generator
    type: qr-code-generator
    inputs:
      - test
      - test2
    templateString:
      - "{{test}} and {{.test2}}"
  - name: Search Business New Again
    type: search
    keyBinding: 1
    searchSettings:
      modifier: control
    fileSettings:
      source: ./CLIENT_INFO.xlsx
      type: xlsx
      sheet: Client Info
      numberOfSkipRows: 6
    fields:
      - name: NEW CODE
        search: true
        displayName: Code
        keyBinding: c
        qr:
          templateString: "https://localhost:8000/test/{{.}}"
      - name: Business Name
        search: true
        primary: true
        displayName: Business
        keyBinding: b
        qr:
          templateString: "{{.}}"
      - name: Office Address / Location
        displayName: Address
      - name: Email
        search: true
        display: true
      - name: Phone Number
        search: true
        displayName: Phone
      - name: Mobile Number
        search: true
        displayName: Mobile
      - name: Name
        displayName: First Name
      - name: Last Name
        display: true
