configuration:
  maxEntries: 10
services:
  - name: Search Code/Name
    sourceFile: ./test.csv
    fileType: csv
    primaryField: Business Name
    searchFields:
      - NEW CODE
      - Business Name
      - Email
      - Phone Number
      - Mobile Number
    displayFields:
      - NEW CODE
      - Business Name
      - Name
      - Last Name
      - Email
      - Phone Number
      - Mobile Number
      - Office Address / Location
    fieldSettings:
      NEW CODE:
        display: Code
      Business Name:
        display: Business
      Name:
        display: First Name
      Office Address / Location:
        display: Address
      Phone Number:
        display: Phone
      Mobile Number:
        display: Mobile
    fileSettings:
      numberSkipRows: 2